# Generated by Django 5.2.8 on 2025-11-14 15:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablereservation",
            name="reservation_period",
        ),
        migrations.AddField(
            model_name="tablereservation",
            name="reservation_duration_hours",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Введите продолжительность бронирования в часах (от 1 до 8)",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="Продолжительность бронирования (часы)",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tablereservation",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
    ]
