# Generated by Django 5.2.8 on 2025-11-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_remove_tablereservation_reservation_period_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tablereservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "ожидание"),
                    ("confirmed", "подтвержлено"),
                    ("canceled", "отменено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
