# Generated by Django 5.2.8 on 2025-11-15 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_tablereservation_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tablereservation",
            name="screenshot",
        ),
        migrations.AddField(
            model_name="table",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="tables/photos/",
                verbose_name="Фото стола",
            ),
        ),
        migrations.AlterField(
            model_name="tablereservation",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Ожидание"),
                    ("confirmed", "Подтверждено"),
                    ("canceled", "Отменено"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
