# Generated by Django 5.2.8 on 2025-11-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_remove_tablereservation_screenshot_table_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="table",
            name="price",
        ),
    ]
